{% set name = "libaec" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.dkrz.de/k202009/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: f9aca467c904bdde73977e6a10454e8bcac86b5cb5eb5a3e547f140babb8cf7b
  # Windows doesn't support the restrict keyword
  #
  #      sed -i "s/restrict /__restrict /" src/*
  #      git diff -u > remove_restrict.diff
  patches:
    - windows_restrict_keyword.diff   # [win]
    - disable_static_cmake.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libaec') }}

requirements:
  build:
    - cmake
    - make     # [not win]
    - ninja    # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libaec${SHLIB_EXT}        # [not win]
    - test -f ${PREFIX}/lib/libsz${SHLIB_EXT}         # [not win]
    - if not exist %LIBRARY_LIB%\\aec.lib exit 1      # [win]
    - if not exist %LIBRARY_BIN%\\aec.dll exit 1      # [win]
    - if not exist %LIBRARY_LIB%\\szip.lib exit 1     # [win]
    - if not exist %LIBRARY_BIN%\\szip.dll exit 1     # [win]
    - if not exist %LIBRARY_INC%\\libaec.h exit 1     # [win]

about:
  home: https://gitlab.dkrz.de/k202009/libaec
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Adaptive Entropy Coding library
  description: |
    Libaec provides fast lossless compression of 1 up to 32 bit wide signed or unsigned integers (samples).
    The library achieves best results for low entropy data as often encountered in space imaging instrument
    data or numerical model output from weather or climate simulations. While floating point representations
    are not directly supported, they can also be efficiently coded by grouping exponents and mantissa.
    Libaec implements Golomb-Rice coding as defined in the Space Data System Standard documents 121.0-B-2
    and 120.0-G-2.
  dev_url: https://gitlab.dkrz.de/k202009/libaec

extra:
  recipe-maintainers:
    - kmuehlbauer
    - hmaarrfk
